'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { KeyRound, LoaderCircle, Pencil, Plus, ShieldCheck, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { apiDelete, apiGet, apiPatch, apiPost } from '@/lib/api/client';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Sheet, SheetBody, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

interface Role { id: number; name: string; permissions?: Array<{ id?: number; name: string }>; users_count?: number }
interface AdminUser { id: number; name: string; email: string; user_type: string; roles: Role[]; created_at: string }
interface UsersMeta { total: number; roles: Role[] }

function UserEditor({ user, roles, onClose }: { user?: AdminUser | null; roles: Role[]; onClose: () => void }) {
  const client = useQueryClient(); const mutation = useMutation({ mutationFn: (body: Record<string, unknown>) => user ? apiPatch(`admin/users/${user.id}`, body) : apiPost('admin/users', body), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['admin-users'] }); onClose(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); mutation.mutate({ ...data, role_id: Number(data.role_id) }); }
  return <form className="flex min-h-0 flex-1 flex-col" onSubmit={submit}><SheetBody className="min-h-0 flex-1 space-y-4 overflow-y-auto px-6">{mutation.isError && <Alert variant="destructive"><AlertDescription>{mutation.error.message}</AlertDescription></Alert>}<div className="space-y-2"><Label>Full name</Label><Input name="name" defaultValue={user?.name} required /></div><div className="space-y-2"><Label>Email</Label><Input name="email" type="email" defaultValue={user?.email} required /></div><div className="space-y-2"><Label>Access role</Label><Select name="role_id" defaultValue={String(user?.roles[0]?.id || roles[0]?.id || '')}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{roles.map((role) => <SelectItem value={String(role.id)} key={role.id}>{role.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>{user ? 'New password (optional)' : 'Password'}</Label><Input name="password" type="password" minLength={8} required={!user} /></div><div className="space-y-2"><Label>Confirm password</Label><Input name="password_confirmation" type="password" minLength={8} required={!user} /></div></SheetBody><SheetFooter className="border-t px-6 py-4"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending && <LoaderCircle className="animate-spin" />}{user ? 'Save user' : 'Create user'}</Button></SheetFooter></form>;
}
export function AdminUsersWorkspace() {
  const client = useQueryClient(); const [editor, setEditor] = useState<AdminUser | 'create' | null>(null);
  const query = useQuery({ queryKey: ['admin-users'], queryFn: () => apiGet<AdminUser[]>('admin/users?per_page=100') }); const meta = query.data?.meta as unknown as UsersMeta | undefined;
  const remove = useMutation({ mutationFn: (id: number) => apiDelete(`admin/users/${id}`), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['admin-users'] }); } });
  return <div className="mx-auto max-w-6xl space-y-5"><div className="flex items-end justify-between gap-4"><div><Badge variant="destructive" appearance="light">Super Admin</Badge><h1 className="mt-2 text-2xl font-semibold">Admin Users</h1><p className="text-sm text-muted-foreground">Manage staff accounts allowed to authenticate to Operations V2.</p></div><Button onClick={() => setEditor('create')}><Plus />Add administrator</Button></div>{query.isError && <Alert variant="destructive"><AlertDescription>{query.error.message}</AlertDescription></Alert>}<Card><CardHeader><div><CardTitle>Authorized staff</CardTitle><CardDescription>{meta?.total || 0} administration accounts</CardDescription></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Role</TableHead><TableHead>Type</TableHead><TableHead>Created</TableHead><TableHead /></TableRow></TableHeader><TableBody>{query.data?.data.map((user) => <TableRow key={user.id}><TableCell><p className="font-medium">{user.name}</p><p className="text-xs text-muted-foreground">{user.email}</p></TableCell><TableCell>{user.roles.map((role) => role.name).join(', ') || 'No role'}</TableCell><TableCell><Badge variant={user.user_type === 'S' ? 'destructive' : 'secondary'} appearance="light">{user.user_type === 'S' ? 'Super Admin' : 'Office Admin'}</Badge></TableCell><TableCell>{new Date(user.created_at).toLocaleDateString()}</TableCell><TableCell><div className="flex justify-end gap-1"><Button mode="icon" variant="ghost" onClick={() => setEditor(user)}><Pencil /></Button>{user.user_type !== 'S' && <Button mode="icon" variant="ghost" className="text-destructive" onClick={() => window.confirm(`Remove access for ${user.name}?`) && remove.mutate(user.id)}><Trash2 /></Button>}</div></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Sheet open={Boolean(editor)} onOpenChange={(open) => !open && setEditor(null)}><SheetContent className="w-full gap-0 p-0 sm:max-w-lg"><SheetHeader className="border-b px-6 py-5 text-start"><SheetTitle>{editor === 'create' ? 'Add administrator' : 'Edit administrator'}</SheetTitle><SheetDescription>Passport access follows this account and its assigned role.</SheetDescription></SheetHeader>{editor && <UserEditor user={editor === 'create' ? null : editor} roles={meta?.roles || []} onClose={() => setEditor(null)} />}</SheetContent></Sheet></div>;
}

function RoleEditor({ role, allPermissions, onClose }: { role?: Role | null; allPermissions: string[]; onClose: () => void }) {
  const client = useQueryClient(); const [permissions, setPermissions] = useState<string[]>(role?.permissions?.map((permission) => permission.name) || []);
  useEffect(() => setPermissions(role?.permissions?.map((permission) => permission.name) || []), [role]);
  const mutation = useMutation({ mutationFn: (body: Record<string, unknown>) => role ? apiPatch(`admin/roles/${role.id}`, body) : apiPost('admin/roles', body), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['admin-roles'] }); onClose(); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); mutation.mutate({ name: String(new FormData(event.currentTarget).get('name') || ''), permissions }); }
  return <form className="flex min-h-0 flex-1 flex-col" onSubmit={submit}><SheetBody className="min-h-0 flex-1 space-y-5 overflow-y-auto px-6">{mutation.isError && <Alert variant="destructive"><AlertDescription>{mutation.error.message}</AlertDescription></Alert>}<div className="space-y-2"><Label>Role name</Label><Input name="name" defaultValue={role?.name} required /></div><div><div className="mb-3 flex items-center justify-between"><Label>Permissions</Label><Button type="button" size="sm" variant="ghost" onClick={() => setPermissions(permissions.length === allPermissions.length ? [] : allPermissions)}>{permissions.length === allPermissions.length ? 'Clear all' : 'Select all'}</Button></div><div className="space-y-2">{allPermissions.map((permission) => <label className="flex items-center gap-3 rounded-lg border p-3" key={permission}><Checkbox checked={permissions.includes(permission)} onCheckedChange={(checked) => setPermissions((current) => checked ? [...current, permission] : current.filter((name) => name !== permission))} /><span className="text-sm">{permission}</span></label>)}</div></div></SheetBody><SheetFooter className="border-t px-6 py-4"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={mutation.isPending}>{mutation.isPending && <LoaderCircle className="animate-spin" />}Save role</Button></SheetFooter></form>;
}
export function AdminRolesWorkspace() {
  const client = useQueryClient(); const [editor, setEditor] = useState<Role | 'create' | null>(null);
  const query = useQuery({ queryKey: ['admin-roles'], queryFn: () => apiGet<{ roles: Role[]; permissions: string[] }>('admin/roles') });
  const remove = useMutation({ mutationFn: (id: number) => apiDelete(`admin/roles/${id}`), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['admin-roles'] }); } });
  return <div className="mx-auto max-w-5xl space-y-5"><div className="flex items-end justify-between gap-4"><div><Badge variant="destructive" appearance="light">Role-based access</Badge><h1 className="mt-2 text-2xl font-semibold">Access Roles</h1><p className="text-sm text-muted-foreground">Assign explicit capabilities while protecting the Super Admin role.</p></div><Button onClick={() => setEditor('create')}><Plus />Add role</Button></div>{query.isError && <Alert variant="destructive"><AlertDescription>{query.error.message}</AlertDescription></Alert>}<div className="grid gap-4 md:grid-cols-2">{query.data?.data.roles.map((role) => <Card key={role.id}><CardContent className="p-5"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary">{role.name === 'Super Admin' ? <KeyRound /> : <ShieldCheck />}</span><div className="flex gap-1"><Button mode="icon" variant="ghost" disabled={role.name === 'Super Admin'} onClick={() => setEditor(role)}><Pencil /></Button><Button mode="icon" variant="ghost" className="text-destructive" disabled={role.name === 'Super Admin' || Boolean(role.users_count)} onClick={() => window.confirm(`Delete ${role.name}?`) && remove.mutate(role.id)}><Trash2 /></Button></div></div><h2 className="mt-4 font-semibold">{role.name}</h2><p className="mt-1 text-sm text-muted-foreground">{role.users_count || 0} users · {role.permissions?.length || 0} permissions</p><div className="mt-4 flex flex-wrap gap-1">{role.permissions?.slice(0, 5).map((permission) => <Badge key={permission.name} variant="secondary" appearance="light" size="sm">{permission.name}</Badge>)}</div></CardContent></Card>)}</div><Sheet open={Boolean(editor)} onOpenChange={(open) => !open && setEditor(null)}><SheetContent className="w-full gap-0 p-0 sm:max-w-xl"><SheetHeader className="border-b px-6 py-5 text-start"><SheetTitle>{editor === 'create' ? 'Add access role' : 'Edit access role'}</SheetTitle><SheetDescription>Permissions are enforced by Laravel and returned in the authenticated session.</SheetDescription></SheetHeader>{editor && <RoleEditor role={editor === 'create' ? null : editor} allPermissions={query.data?.data.permissions || []} onClose={() => setEditor(null)} />}</SheetContent></Sheet></div>;
}
