'use client';

import { FormEvent, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { useMutation, useQuery } from '@tanstack/react-query';
import { ClipboardCheck, LoaderCircle } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiRequest } from '@/lib/api/client';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

interface RegistrationOptions { drivers: Record<string, string> }
interface Checklist { id: number; title: string; weight: number; assessment_type: string; meta?: { items?: Array<string | { question?: string; keywords?: string[] }> | Record<string, { question?: string }> } }
interface Assessment { driver: { id: number; driver_code: string; driver_type: string; employment_relation: string; person?: Record<string, unknown> }; registration: Record<string, unknown>; course?: { id: number; title: string; pass_mark: number; checklists: Checklist[] }; latest_result?: Record<string, unknown>; training_options: string[]; fleet_assets: Record<string, string>; selected_fleet_asset_id?: number }
function Field({ name, label, type = 'text' }: { name: string; label: string; type?: string }) { return <div className="space-y-2"><Label>{label}</Label><Input name={name} type={type} /></div>; }
export function AcademyTest() {
  const params = useSearchParams(); const router = useRouter(); const [driverId, setDriverId] = useState(params.get('driver_id') || '');
  const drivers = useQuery({ queryKey: ['academy-registration-options'], queryFn: () => apiGet<RegistrationOptions>('academy/registration/options') });
  const assessment = useQuery({ queryKey: ['academy-assessment', driverId], queryFn: () => apiGet<Assessment>(`academy/drivers/${driverId}/assessment`), enabled: Boolean(driverId) });
  const mutation = useMutation({ mutationFn: (body: FormData) => apiRequest<{ result: Record<string, unknown> }>('academy/assessments', { method: 'POST', body }), onSuccess: (result) => { toast.success(result.message); router.push('/ops/academy'); } });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const body = new FormData(event.currentTarget); if (body.get('final_decision_override') === 'automatic') body.delete('final_decision_override'); if (body.get('fleet_asset_id') === 'new_asset') body.delete('fleet_asset_id'); for (const [key, value] of [...body.entries()]) { if (value === 'not_checked') body.delete(key); } mutation.mutate(body); }
  const data = assessment.data?.data; const course = data?.course;
  return <div className="mx-auto max-w-6xl space-y-5"><div><Badge variant="info" appearance="light">Scored workflow</Badge><h1 className="mt-2 text-2xl font-semibold">Driver Testing Checklist</h1><p className="mt-1 text-sm text-muted-foreground">Road test, vehicle inspection, customer care, scenario answers and auditable approval.</p></div>
    <Card><CardHeader><div><CardTitle>Select driver</CardTitle><CardDescription>Only registered drivers with an active matching academy course can be assessed.</CardDescription></div></CardHeader><CardContent><Select value={driverId} onValueChange={setDriverId}><SelectTrigger><SelectValue placeholder="Choose driver going for testing" /></SelectTrigger><SelectContent>{Object.entries(drivers.data?.data.drivers || {}).filter(([id]) => id).map(([id, label]) => <SelectItem value={id} key={id}>{label}</SelectItem>)}</SelectContent></Select></CardContent></Card>
    {driverId && assessment.isLoading && <Card><CardContent className="py-14 text-center">Loading assessment and course…</CardContent></Card>}
    {assessment.isError && <Alert variant="destructive"><AlertDescription>{assessment.error.message}</AlertDescription></Alert>}
    {data && course && <form onSubmit={submit} className="space-y-5"><input type="hidden" name="driver_id" value={driverId} /><input type="hidden" name="academy_course_id" value={course.id} />
      {mutation.isError && <Alert variant="destructive"><AlertDescription>{mutation.error.message}</AlertDescription></Alert>}
      <Card><CardHeader><div><CardTitle>Assessment details</CardTitle><CardDescription>{course.title} · Pass mark {course.pass_mark}%</CardDescription></div></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><div className="rounded-lg bg-muted/50 p-3"><p className="text-xs text-muted-foreground">Driver</p><p className="font-medium">{String(data.driver.person?.full_name || data.driver.driver_code)}</p></div><div className="space-y-2"><Label>Assessment date</Label><Input name="assessment_date" type="date" defaultValue={new Date().toISOString().slice(0, 10)} /></div><div className="space-y-2"><Label>Assessment type</Label><Select name="assessment_type" defaultValue="road_test"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['road_test', 'mystery_client_test', 'office_interview', 'vehicle_inspection', 'final_approval'].map((value) => <SelectItem value={value} key={value}>{value.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select></div><Field name="assessor_name" label="Assessor name" /><Field name="assessor_position" label="Assessor position" /><div className="space-y-2"><Label>Vehicle result</Label><Select name="vehicle_result" defaultValue="passed"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['passed', 'passed_with_conditions', 'failed', 'not_applicable'].map((value) => <SelectItem value={value} key={value}>{value.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
      <Card><CardHeader><CardTitle>Vehicle & route</CardTitle><CardDescription>Link an existing fleet asset, or enter a plate below and the tested vehicle will be added to fleet assets automatically.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3"><div className="space-y-2 md:col-span-3"><Label>Existing fleet asset (optional)</Label><Select name="fleet_asset_id" defaultValue={data.selected_fleet_asset_id ? String(data.selected_fleet_asset_id) : 'new_asset'}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="new_asset">Create or match from vehicle plate</SelectItem>{Object.entries(data.fleet_assets || {}).map(([id, label]) => <SelectItem key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div>{[['vehicle_brand', 'Vehicle brand'], ['vehicle_model', 'Vehicle model'], ['vehicle_year', 'Year'], ['vehicle_color', 'Color'], ['vehicle_number_plate', 'Number plate'], ['start_location', 'Start location'], ['route_area_tested', 'Route / area tested'], ['end_location', 'End location'], ['route_other', 'Other route type']].map(([name, label]) => <Field key={name} name={name} label={label} />)}<div className="space-y-2"><Label>Vehicle ownership</Label><Select name="vehicle_ownership" defaultValue="company_vehicle"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['company_vehicle', 'driver_owned', 'authorized_vehicle'].map((value) => <SelectItem key={value} value={value}>{value.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select></div><div className="md:col-span-3"><p className="mb-3 text-sm font-medium">Route coverage</p><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-3">{['normal_town_road', 'traffic_jam', 'roundabout_junction', 'parking_test', 'reverse_test', 'hill_slope', 'rough_road', 'hotel_office_pickup', 'airport_style_pickup'].map((value) => <label className="flex items-center gap-2 rounded-lg border p-3 text-sm" key={value}><input type="checkbox" name="route_types[]" value={value} />{value.replaceAll('_', ' ')}</label>)}</div></div></CardContent></Card>
      {course.checklists.map((checklist) => { const items = Array.isArray(checklist.meta?.items) ? checklist.meta.items : Object.entries(checklist.meta?.items || {}).map(([key, value]) => ({ ...value, key })); return <Card key={checklist.id}><CardHeader><div><CardTitle>{checklist.title}</CardTitle><CardDescription>{checklist.assessment_type.replaceAll('_', ' ')} · weight {checklist.weight}</CardDescription></div>{checklist.assessment_type !== 'scenario_answers' && <div className="w-36 space-y-1"><Label>Manual score</Label><Input name={`scores[${checklist.id}]`} type="number" min="0" max={checklist.weight} step="0.01" /></div>}</CardHeader><CardContent className="space-y-3">{items.map((item, index) => { const object = typeof item === 'string' ? { question: item, key: item.toLowerCase().replace(/[^a-z0-9]+/g, '_') } : item; const key = 'key' in object ? String(object.key) : `item_${index}`; return checklist.assessment_type === 'scenario_answers' ? <div className="space-y-2 rounded-lg border p-3" key={key}><Label>{object.question || key}</Label><Textarea name={`scenario_answers[${key}]`} rows={2} /></div> : <div className="grid items-center gap-3 rounded-lg border p-3 md:grid-cols-[1fr_180px_1fr]" key={key}><p className="text-sm font-medium">{object.question || (typeof item === 'string' ? item : key)}</p><Select name={`item_details[${checklist.id}][${key}][rating]`} defaultValue="not_checked"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['not_checked', 'good', 'fair', 'poor', 'passed', 'failed', 'not_tested'].map((value) => <SelectItem key={value} value={value}>{value.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select><Input name={`item_details[${checklist.id}][${key}][notes]`} placeholder="Notes" /></div>; })}<div className="space-y-2"><Label>Section notes</Label><Textarea name={`item_notes[${checklist.id}]`} rows={2} /></div></CardContent></Card>; })}
      <Card><CardHeader><CardTitle>Final decision & approvals</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><p className="mb-3 text-sm font-medium">Training needed</p><div className="grid gap-2 sm:grid-cols-2 md:grid-cols-4">{data.training_options.map((value) => <label className="flex items-center gap-2 rounded-lg border p-3 text-sm" key={value}><input type="checkbox" name="training_needed[]" value={value} />{value.replaceAll('_', ' ')}</label>)}</div></div><Field name="training_other" label="Other training" /><div className="space-y-2"><Label>Final decision override</Label><Select name="final_decision_override" defaultValue="automatic"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="automatic">Use score guide automatically</SelectItem>{['approved', 'approved_with_training', 'needs_second_test', 'not_approved', 'requires_vehicle_reinspection', 'requires_management_review'].map((value) => <SelectItem key={value} value={value}>{value.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select></div><Field name="driver_acknowledgment_name" label="Driver acknowledgment name" /><Field name="driver_acknowledgment_date" label="Acknowledgment date" type="date" /><Field name="driver_signature_reference" label="Signature reference" /><Field name="assessor_approval_name" label="Assessor approval name" /><Field name="assessor_approval_position" label="Assessor position" /><Field name="assessor_approval_date" label="Approval date" type="date" /><Field name="company_stamp_reference" label="Company stamp reference" /><div className="space-y-2 md:col-span-2"><Label>Supervisor notes</Label><Textarea name="notes" rows={4} /></div></CardContent></Card><div className="flex justify-end"><Button size="lg" disabled={mutation.isPending}>{mutation.isPending ? <LoaderCircle className="animate-spin" /> : <ClipboardCheck />}Save test and calculate result</Button></div>
    </form>}
    {data && !course && <Alert><AlertDescription>No active matching academy course is configured for this driver.</AlertDescription></Alert>}
  </div>;
}
