'use client';

import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Banknote, Calculator, RefreshCw, UserRound } from 'lucide-react';
import { toast } from 'sonner';
import { apiGet, apiPost, apiRequest } from '@/lib/api/client';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { ValueDisplay, formatLabel } from '@/features/resources/value-display';

interface Profile { driver: Record<string, unknown> & { id: number; person?: Record<string, unknown> }; ledger: Record<string, unknown>; calendar: Array<Record<string, unknown>>; payments: Array<Record<string, unknown>>; welfare_funds: Array<Record<string, unknown>> }
const KPI_KEYS = ['total_expected', 'total_paid', 'total_owed', 'credit_balance', 'waived_amount', 'welfare_outstanding'];
export function RemittanceProfile({ driverId }: { driverId: number }) {
  const client = useQueryClient();
  const query = useQuery({ queryKey: ['remittance-profile', driverId], queryFn: () => apiGet<Profile>(`remittance/drivers/${driverId}`) });
  const recalc = useMutation({ mutationFn: () => apiPost(`remittance/drivers/${driverId}/recalculate`), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['remittance-profile', driverId] }); } });
  const repair = useMutation({ mutationFn: () => apiPost('remittance/repair-future-allocations', { driver_id: driverId, dry_run: false, confirmation: 'REPAIR_FUTURE_ALLOCATIONS' }), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['remittance-profile', driverId] }); } });
  const removePayment = useMutation({ mutationFn: (id: number) => apiRequest(`remittance/payments/${id}`, { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmation: 'DELETE_PAYMENT_BATCH' }) }), onSuccess: (result) => { toast.success(result.message); void client.invalidateQueries({ queryKey: ['remittance-profile', driverId] }); } });
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-24" /><Skeleton className="h-80" /></div>;
  if (!query.data) return <Card><CardContent className="py-14 text-center"><p>{query.error?.message || 'Driver profile not found.'}</p><Button className="mt-4" asChild><Link href="/ops/remittance/assigned">Back to assigned drivers</Link></Button></CardContent></Card>;
  const { driver, ledger, calendar, payments, welfare_funds: welfare } = query.data.data; const person = driver.person || {};
  return <div className="mx-auto max-w-[1600px] space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-xl bg-primary/10 text-primary"><UserRound /></span><div><Badge variant="success" appearance="light">{String(driver.approval_status || 'driver')}</Badge><h1 className="mt-1 text-2xl font-semibold">{String(person.full_name || driver.driver_code || `Driver #${driverId}`)}</h1><p className="text-sm text-muted-foreground">{String(driver.driver_code || '')} · {String(driver.driver_type || '')} · {String(driver.employment_relation || '').replaceAll('_', ' ')}</p></div></div><div className="flex flex-wrap gap-2"><Button asChild><Link href={`/ops/remittance/payments/create?driver_id=${driverId}`}><Banknote />Record payment</Link></Button><Button asChild variant="outline"><Link href={`/ops/manage/driver-welfare-funds?create=1&driver_id=${driverId}`}>Welfare fund</Link></Button><Button asChild variant="outline"><Link href={`/ops/manage/remittance-adjustments?create=1&driver_id=${driverId}`}>Excuse / waiver</Link></Button><Button variant="outline" onClick={() => recalc.mutate()} disabled={recalc.isPending}><Calculator />Recalculate</Button><Button variant="outline" onClick={() => window.confirm('Repair future paid-day allocations for this driver and recalculate balances?') && repair.mutate()} disabled={repair.isPending}><RefreshCw />Repair allocations</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{KPI_KEYS.map((key) => <Card key={key}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{formatLabel(key)}</p><p className="mt-2 text-xl font-semibold">{Number(ledger[key] || 0).toLocaleString()}</p></CardContent></Card>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1fr_1.3fr]"><Card><CardHeader><div><CardTitle>Profile & credentials</CardTitle><CardDescription>Identity and operational readiness details.</CardDescription></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{Object.entries({ 'Driver code': driver.driver_code, 'Full name': person.full_name, Phone: person.phone, 'Alternative phone': person.alternative_phone, Email: person.email, Address: person.address, 'National ID / NIN': person.national_id_number, 'Driver status': driver.approval_status, 'Academy status': driver.academy_status, 'Arrears days': ledger.days_in_arrears, 'Last payment': ledger.last_payment_date }).map(([label, value]) => <div key={label} className="rounded-lg bg-muted/50 p-3"><p className="text-[10px] font-semibold uppercase text-muted-foreground">{label}</p><div className="mt-1 text-sm font-medium"><ValueDisplay value={value} field={label} /></div></div>)}</CardContent></Card><Card><CardHeader><div><CardTitle>Contract ledger summary</CardTitle><CardDescription>Current contract-derived calendar and balance controls.</CardDescription></div></CardHeader><CardContent className="grid gap-3 sm:grid-cols-3">{Object.entries(ledger).filter(([, value]) => typeof value !== 'object').slice(0, 18).map(([key, value]) => <div key={key} className="rounded-lg border p-3"><p className="text-[10px] uppercase text-muted-foreground">{formatLabel(key)}</p><p className="mt-1 text-sm font-medium">{String(value ?? '—')}</p></div>)}</CardContent></Card></div>
    <Card><CardHeader><div><CardTitle>Contract remittance calendar</CardTitle><CardDescription>{calendar.length} due items from contract start.</CardDescription></div></CardHeader><CardContent className="max-h-[520px] overflow-auto p-0"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Type</TableHead><TableHead>Expected</TableHead><TableHead>Welfare</TableHead><TableHead>Paid</TableHead><TableHead>Waived</TableHead><TableHead>Balance</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{calendar.map((day) => <TableRow key={String(day.id)}><TableCell>{String(day.remittance_date || '—')}</TableCell><TableCell>{String(day.day_type || '—').replaceAll('_', ' ')}</TableCell><TableCell>{Number(day.expected_amount || 0).toLocaleString()}</TableCell><TableCell>{Number(day.welfare_due || 0).toLocaleString()}</TableCell><TableCell>{Number(day.actual_paid || 0).toLocaleString()}</TableCell><TableCell>{Number(day.waived_amount || 0).toLocaleString()}</TableCell><TableCell>{Number(day.balance || 0).toLocaleString()}</TableCell><TableCell><ValueDisplay value={day.status} field="status" /></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><div><CardTitle>Payment history</CardTitle><CardDescription>{payments.length} posted batches.</CardDescription></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Amount</TableHead><TableHead>Allocated</TableHead><TableHead>Credit</TableHead><TableHead>Method</TableHead><TableHead /></TableRow></TableHeader><TableBody>{payments.map((payment) => <TableRow key={String(payment.id)}><TableCell>{String(payment.payment_date || '—')}</TableCell><TableCell>{Number(payment.amount || 0).toLocaleString()}</TableCell><TableCell>{Number(payment.allocated_amount || 0).toLocaleString()}</TableCell><TableCell>{Number(payment.credit_amount || 0).toLocaleString()}</TableCell><TableCell>{String(payment.payment_method || '').replaceAll('_', ' ')}</TableCell><TableCell><Button size="sm" variant="ghost" className="text-destructive" disabled={removePayment.isPending} onClick={() => window.confirm('Delete this mistaken payment batch and recalculate all affected balances?') && removePayment.mutate(Number(payment.id))}>Delete mistaken</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card><CardHeader><div><CardTitle>Welfare funds</CardTitle><CardDescription>{welfare.length} records affecting remittance.</CardDescription></div></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Status</TableHead><TableHead>Issued</TableHead><TableHead>Principal</TableHead><TableHead>Repaid</TableHead><TableHead>Outstanding</TableHead></TableRow></TableHeader><TableBody>{welfare.map((fund) => <TableRow key={String(fund.id)}><TableCell><ValueDisplay value={fund.status} field="status" /></TableCell><TableCell>{String(fund.issued_on || '—')}</TableCell><TableCell>{Number(fund.principal_amount || 0).toLocaleString()}</TableCell><TableCell>{Number(fund.amount_repaid || 0).toLocaleString()}</TableCell><TableCell>{Number(fund.outstanding_balance || 0).toLocaleString()}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
  </div>;
}
