import { Download, ExternalLink, Pencil, Zap } from 'lucide-react';
import { ResourceRecord, ResourceSchema } from '@/types/api';
import { Button } from '@/components/ui/button';
import { SheetBody } from '@/components/ui/sheet';
import { ValueDisplay } from './value-display';
import { FleetAssetMedia } from '@/features/assets/fleet-asset-media';

export function ResourceDetails({ schema, record, onEdit, onAction, actionBusy = false }: { schema: ResourceSchema; record: ResourceRecord; onEdit?: () => void; onAction?: (action: string) => void; actionBusy?: boolean }) {
  const hiddenFields = schema.resource === 'documents' ? new Set(['file_path', 'legacy_disk', 'has_file']) : new Set<string>();
  const documentUrl = `/api/backend/documents/${record.id}/content`;
  const hasDocument = schema.resource === 'documents' && Boolean(record.has_file ?? record.file_path);

  return <SheetBody className="space-y-5 overflow-y-auto px-6">{onEdit && <Button type="button" className="w-full" onClick={onEdit}><Pencil />Edit {schema.singular}</Button>}{onAction && Object.keys(schema.actions).length > 0 && <div className="grid gap-2 sm:grid-cols-2">{Object.entries(schema.actions).map(([action, label]) => <Button key={action} type="button" variant="outline" disabled={actionBusy} onClick={() => onAction(action)}><Zap />{label}</Button>)}</div>}{hasDocument && <div className="overflow-hidden rounded-xl border bg-muted/20"><iframe className="h-[420px] w-full bg-white" src={documentUrl} title={String(record.title || 'Document preview')} /></div>}<div className="grid gap-3 sm:grid-cols-2">{Object.entries(record).filter(([field]) => !hiddenFields.has(field)).map(([field, value]) => <div key={field} className="rounded-lg border p-3"><p className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-muted-foreground">{schema.fields[field]?.label || schema.columns[field] || field.replaceAll('_', ' ')}</p><ValueDisplay value={value} field={field} lookup={schema.lookups[field]} /></div>)}</div>{schema.resource === 'documents' && (hasDocument ? <div className="grid gap-2 sm:grid-cols-2"><Button asChild><a href={documentUrl} target="_blank" rel="noreferrer"><ExternalLink />Open full preview</a></Button><Button asChild variant="outline"><a href={`${documentUrl}?download=1`}><Download />Download document</a></Button></div> : <div className="rounded-lg border border-dashed p-4 text-center text-sm text-muted-foreground">No file has been uploaded for this document.</div>)}{schema.resource === 'fleet-assets' && <FleetAssetMedia assetId={Number(record.id)} />}{schema.resource === 'invoices' && <Button asChild variant="outline" className="w-full"><a href={`/api/backend/invoices/${record.id}/print-data`} target="_blank" rel="noreferrer"><ExternalLink />Open invoice data</a></Button>}</SheetBody>;
}
